/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package XYG_BARGRAPH;

import XYG_BASIC.MyGraphContainer;
import XYG_BASIC.MyPoint;
import XYG_STATS.BarGraphListener;
import XYG_STATS.BasicGraphListener;
import XYG_STATS.XyGraph_M;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import other.StringDouble;

/**
 *
 * @author KOCMOC
 */
public class RUN_B extends javax.swing.JFrame implements BarGraphListener {

    private BasicGraphListener gg_a;
    private MyGraphXY_BG mgxyhm_a;
    private final XyGraph_M xygraph_a = new XyGraph_M("Test BG-A", MyGraphContainer.DISPLAY_MODE_FULL_SCREEN);
    //
    //
    private BasicGraphListener gg_b;
    private MyGraphXY_BG mgxyhm_b;
    private final XyGraph_M xygraph_b = new XyGraph_M("Test BG-B", MyGraphContainer.DISPLAY_MODE_FULL_SCREEN);

    /**
     * Creates new form RUN_B
     */
    public RUN_B() {
        initComponents();
        init();
    }

    private void init() {
        //
        this.mgxyhm_a = new MyGraphXY_BG("Total",":-");
        this.mgxyhm_a.addBarGraphListener(this);
        this.gg_a = new BARGraph("Test BG-A", mgxyhm_a, MyGraphContainer.DISPLAY_MODE_FULL_SCREEN); // MyGraphContainer.DISPLAY_MODE_FOOT_DISABLED
        //
        //
        this.mgxyhm_b = new MyGraphXY_BG("Antal"," st");
        this.mgxyhm_b.addBarGraphListener(this);
        this.gg_b = new BARGraph("Test BG-B", mgxyhm_b, MyGraphContainer.DISPLAY_MODE_FULL_SCREEN); // MyGraphContainer.DISPLAY_MODE_FOOT_DISABLED
        //
        //
        jPanel1.add(gg_a.getGraph());
        jPanel2.add(gg_b.getGraph());
        //
        new Thread(() -> {
            //
            ArrayList<StringDouble> vl = new ArrayList<>();
            vl.add(new StringDouble("Jan", 47900));
            vl.add(new StringDouble("Feb", 69800));
            vl.add(new StringDouble("Mar", 36010));
            vl.add(new StringDouble("Apr", 52310));
            vl.add(new StringDouble("Maj", 89900));
            vl.add(new StringDouble("Jun", 58900));
            vl.add(new StringDouble("Juli", 78600));
            vl.add(new StringDouble("Aug", 71298));
            vl.add(new StringDouble("Sept", 36789));
            vl.add(new StringDouble("Okt", 98767));
            vl.add(new StringDouble("Nov", 43987));
            vl.add(new StringDouble("Dec", 55436));
            //
            java.awt.EventQueue.invokeLater(() -> {
                //
                BARGraph barg_a = (BARGraph) gg_a;
                barg_a.addData(vl);
                //
                BARGraph barg_b = (BARGraph) gg_b;
                barg_b.addData(vl);
                //
            });
            //
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("DRAW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUN_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUN_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUN_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUN_B.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RUN_B().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void barGraphHoverEvent(MouseEvent e, MyPoint point) {
    }

    @Override
    public void barGraphHoverOutEvent(MouseEvent e) {
    }
}
